name: AWS Workflow
on: 
  push:
    branches:
      - main

env:
  AWS_REGION: "ap-northeast-2"  

permissions:
  id-token: write
  contents: read 

jobs:
  terraform-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3  
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ASSUME }}
          role-session-name: github-actions-session
          aws-region: ${{ env.AWS_REGION }}  
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.5
      - name: Terraform Format
        run: terraform fmt -check  
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan -input=false
      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
            